[package]
name = "peertube"
version = "0.0.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"
description = "Peertube API"
license = "MIT"

[dependencies]
thiserror = "1.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
dotenv = "0.15"
env_logger = "0.8"
tokio-test = "0.4"
